Pt4
rosaigor138/project_college pull request #1
Opened 2022-07-19 22:52 UTC by rosaigor138

2022-07-19 22:57 UTC, pimentabsi requested changes

2022-07-19 22:57 UTC, pimentabsi commented on src/integrantes/informacao/Aluno.java
> -
Linha desnecessária.

2022-07-19 22:57 UTC, pimentabsi commented on src/integrantes/informacao/Aluno.java
> +    private static LocalDate date;
```suggestion
    private static LocalDate anoDaMatricula;
```

2022-07-19 22:58 UTC, rosaigor138 commented on src/integrantes/informacao/Aluno.java
> -
6 e 7 foram linhas já excluidas

2022-07-19 23:00 UTC, pimentabsi approved these changes

2022-07-20 14:02 UTC, fsoupimenta approved these changes

2022-07-20 14:03 UTC, merged